# When changing this file, don't forget to update .pre-commit-config-docker.yaml as well
repos:
-   repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: .env/bin/pylint
        language: system
        types: [python]
        require_serial: false
        args: [--rcfile=pylint.rc, --jobs=0]
